name: CI-Build

on:
  push:
  pull_request:
  schedule:
    - cron:  '21 21 * * *'
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run installer
        shell: pwsh
        run: |
          #curl https://github.com/axonivy-market/iis-proxy/raw/refs/heads/master/scripts/iis-proxy-setup.ps1 -OutFile "iis-proxy-setup.ps1"
          # Execute the PowerShell script
          ls
          ./scripts/iis-proxy-setup.ps1
          cat scripts/*.log

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: script-logs
          path: scripts/*.log
      