name: CI-Build

on:
  push:
  pull_request:
  schedule:
    - cron:  '21 21 * * *'
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write


jobs:
  build:
    strategy:
      matrix:
        platform: [2022, 2025]
        include:
          - platform: 2022
            runner: windows-2022
          - platform: 2025
            runner: windows-2025
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run installer (fetching modules)
        shell: pwsh
        run: |
          Get-WindowsFeature -name web-*
          ./scripts/iis-proxy-setup.ps1
          Get-WindowsFeature -name web-*
          cat scripts/*.log
        env:
          AUTO_CONFIRM: 'true'  # say yes to all prompts

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: script-logs-${{ matrix.runner }}
          path: scripts/*.log
