name: CI-Build

on:
  push:
  pull_request:
  schedule:
    - cron:  '21 21 * * *'
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write


jobs:
  build:
    strategy:
      matrix:
        platform: [2022, 2025]
        include:
          - platform: 2022
            runner: windows-2022
          - platform: 2025
            runner: windows-2025
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run installer (fetching modules)
        shell: pwsh
        run: |
          #Get-WindowsFeature -name web-*
          #& "$env:SystemRoot\System32\inetsrv\appcmd.exe" list modules

          . ./.github/workflows/e2e-test.ps1  # load e2e test functions
          runIvyEngine https://developer.axonivy.com/permalink/nightly/axonivy-engine-windows.zip

          ./scripts/iis-proxy-setup.ps1
          & "$env:SystemRoot\System32\inetsrv\appcmd.exe" list modules
          & "$env:SystemRoot\System32\inetsrv\appcmd.exe" list sites

          Write-Output "Calling engine directly"
          call http://localhost:8080/api/engine/info

          createIISUser admin admin
          enableIvyYamlSSO

          Write-Output "Calling engine via IIS Proxy"
          call http://localhost/api/me

          Write-Output "Enabling HTTPS on IIS Proxy (self-signed)"
          $cert = New-SelfSignedCertificate -DnsName "localhost" -CertStoreLocation "cert:\LocalMachine\My"
          $thumb = $cert.Thumbprint
          netsh http add sslcert ipport=0.0.0.0:443 certhash=$thumb appid='{00112233-4455-6677-8899-AABBCCDDEEFF}'

          Write-Output "Calling engine via IIS Proxy using HTTPS"
          call https://localhost/api/me
        env:
          AUTO_CONFIRM: 'true'  # say yes to all prompts

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: script-logs-${{ matrix.runner }}
          path: '**/*.log'
