name: CI-Build

on:
  push:
  pull_request:
  schedule:
    - cron:  '21 21 * * *'
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run installer (fetching modules)
        shell: pwsh
        run: |
          ./scripts/iis-proxy-setup.ps1
          cat scripts/*.log
        env:
          IIS_MODULES_DOWNLOAD: 'true'  # force download of modules for CI

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: script-logs
          path: scripts/*.log
      